import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(await readFile(resolve(root, "Info.json"), "utf8"));

if (manifest.entry !== "dist/index.js") throw new Error("Info.json entry must be dist/index.js");
if (!Array.isArray(manifest.permissions) || !manifest.permissions.includes("network-request")) {
  throw new Error("Info.json must declare network-request");
}

const core = await readFile(resolve(root, "src/xtream-core.js"), "utf8");
const runtime = await readFile(resolve(root, "src/index.js"), "utf8");
const banner = `/* ${manifest.name} ${manifest.version} — generated by scripts/build.mjs */\n`;

await rm(resolve(root, "dist"), { recursive: true, force: true });
await mkdir(resolve(root, "dist"), { recursive: true });
await writeFile(resolve(root, "dist/index.js"), `${banner}${core}\n${runtime}\n`, "utf8");

console.log(`Built ${manifest.entry}`);

